### ISSUE TITLE
Code Audit

### ISSUE THREAD

**Issue by romeboards** [romeboards/justfixnyc#22]
- General onboarding
- Any questions on current functionality or business requirements
- Identify any improvements to architecture, libraries, etc

**Comment by romeboards** [comment]
Feedback on AWS image uploading process would be cool too -

**Comment by Meegan** [comment]
Code restructuring should be handled here as well.

URL For user object (think it's easier to approach with this methodology):

https://docs.google.com/document/d/1jeYLeY5p07XZ_sLvrtVO-Q-5PFD8g_DgXN-fGlYBXYM/edit?usp=sharing
