### ISSUE TITLE
Tenant landing page

### ISSUE THREAD

**Issue by romeboards** [romeboards/justfixnyc#43]

**Comment by atreni** [comment]
- Update content on the Manifesto and About Us section to reflect current concept note
- Time permitting, add partner logos (in folder on dropbox)

**Comment by atreni** [comment]
- Really large white space before “Build Your Case” on mobile
- Decrease block width on Steps (small text) to 400pt
- Button text size too wide (desktop); text is also really big

**Comment by romeboards** [comment]
- Needs Sign In link

**Comment by romeboards** [comment]
http://stackoverflow.com/questions/14388367/mobile-safari-window-height-url-bar-discrepancy
